apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: goals-cluster-01
  region: us-east-1
  version: "1.34"
iam:
  withOIDC: true

vpc:
  id: vpc-0f47352a27e77ed6c
  subnets:
    private:
      us-east-1b:
        id: subnet-06ef563e2fd0d0c2e
      us-east-1f:
        id: subnet-0ab6652b231e6ad53
      us-east-1e: 
        id: subnet-0421fd548df0621b9
      us-east-1d:
        id: subnet-0519ff8e8feb8009a
      us-east-1c:
        id: subnet-09e6bf911af45bcee

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 50
    privateNetworking: true
    ssh:
      allow: false

addons:
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy