apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: goals-cluster-01
  region: us-east-1
  version: "1.34"
iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 50
    ssh:
      allow: false

addons:
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy